# 初始化openstack集群环境 （controller、compute、cinder...）
- hosts: controller compute
  roles:
    - prepare

# 安装keystone服务  （controller）
- hosts: controller
  roles:
    - keystone

# 安装glance服务    （controller）
- hosts: controller
  roles:
    - glance

# 安装nova服务  （controller、compute）
- hosts: controller compute
  roles:
    - nova

# 安装neutron服务   （controller、compute）
- hosts: controller compute
  roles:
    - neutron

# 安装dashboard服务 （controller）
- hosts: controller
  roles:
    - dashboard