- name: controller 安装neutron服务组件
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - openstack-neutron
      - openstack-neutron-ml2
      - openstack-neutron-linuxbridge
  when: (ansible_hostname == "controller")
  
- name: controller 修改配置文件/etc/neutron/neutron.conf
  copy:
    src: controller_neutron.conf
    dest: /etc/neutron/neutron.conf
    owner: root
    group: neutron
    mode: '0640'
  when: (ansible_hostname == "controller")
  
- name: controller 修改配置文件/etc/neutron/plugins/ml2/ml2_conf.ini
  copy:
    src: controller_ml2_conf.ini
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    owner: root
    group: neutron
    mode: '0640'
  when: (ansible_hostname == "controller")
  
- name: controller 修改配置文件/etc/neutron/plugins/ml2/linuxbridge_agent.ini
  template:
    src: controller_linuxbridge_agent.ini
    dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
    owner: root
    group: neutron
    mode: '0640'
  when: (ansible_hostname == "controller")
  
- name: controller 修改配置文件/etc/neutron/l3_agent.ini
  copy:
    src: controller_l3_agent.ini
    dest: /etc/neutron/l3_agent.ini
    owner: root
    group: neutron
    mode: '0640'
  when: (ansible_hostname == "controller")
  
- name: controller 修改配置文件/etc/neutron/dhcp_agent.ini
  copy:
    src: controller_dhcp_agent.ini
    dest: /etc/neutron/dhcp_agent.ini
    owner: root
    group: neutron
    mode: '0640'
  when: (ansible_hostname == "controller")

- name: controller 修改配置文件/etc/neutron/metadata_agent.ini
  copy:
    src: controller_metadata_agent.ini
    dest: /etc/neutron/metadata_agent.ini
    owner: root
    group: neutron
    mode: '0640'
  when: (ansible_hostname == "controller")
  
- name: controller 修改配置文件/etc/nova/nova.conf
  template:
    src: controller_nova.conf
    dest: /etc/nova/nova.conf
    owner: root
    group: nova
    mode: '0640'
  when: (ansible_hostname == "controller")

- name: controller 创建链接文件
  shell: ln -s /etc/neutron/plugins/ml2/ml2_conf.ini /etc/neutron/plugin.ini
  when: (ansible_hostname == "controller")

- name: controller 同步数据库
  shell: su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head" neutron
  when: (ansible_hostname == "controller")

- name: controller 重启nova-api服务
  systemd:
    name: openstack-nova-api
    state: restarted
  when: (ansible_hostname == "controller")

- name: controller 启动neutron相关服务并设置开机自启动
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - neutron-server
    - neutron-linuxbridge-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
  when: (ansible_hostname == "controller")

- name: controller 启动neutron-l3-agent服务并设置开机自启
  systemd:
    name: neutron-l3-agent
    state: started
    enabled: yes
  when: (ansible_hostname == "controller")
    